Throw error immediately if unable to initialize WebGL
Previously, if WebGL couldn't be initialized due to missing Mesa
drivers or similar problem, the 'new GL(...)' call returned 'null',
which was ignored silently until a confusing error deep inside
three.js's initialization:

  TypeError: Cannot read property 'getExtension' of undefined

Now should throw an immediate error for this case, making it a bit
clearer what's going on.

Change-Id: I07084f5b70c8cf13f16e3ed32bb1aa6a932f2fcd