Build requires libgif-dev
On Debian stretch when building 'canvas' depends on libgif-dev:

In file included from ../src/CanvasPattern.cc:9:0:
../src/Image.h:19:21: fatal error: gif_lib.h: No such file or directory
 #include <gif_lib.h>
                     ^
compilation terminated.
canvas.target.mk:122: recipe for target
'Release/obj.target/canvas/src/CanvasPattern.o' failed

Change-Id: Icbd4575d09e0c64098687fb1d273154d16608672